# Google App Engine configuration
runtime: nodejs18

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65

handlers:
- url: /static
  static_dir: build/static
  secure: always
  expiration: "1y"

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always

env_variables:
  NODE_ENV: "production"
