/**
 * Advanced Reporting & Export
 * Comprehensive report generation with all analytics
 */

import React, { useState } from 'react';
import { saveAs } from 'file-saver';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';
import CloudPricingAPI from '../utils/cloudPricingAPI';
import AdvancedAnalytics from '../utils/advancedAnalytics';

const AdvancedReportGenerator = ({ analysisData, companyName = 'Your Company' }) => {
  const [reportFormat, setReportFormat] = useState('pdf');
  const [reportType, setReportType] = useState('executive');
  const [isGenerating, setIsGenerating] = useState(false);

  // Generate comprehensive report data
  const generateReportData = () => {
    if (!analysisData) return null;

    const { tcoResults, analytics } = analysisData;
    
    return {
      executiveSummary: {
        totalInvestment: tcoResults?.totalCloudTCO || 0,
        totalSavings: tcoResults?.savings || 0,
        roi: tcoResults?.roi || 0,
        timeframe: tcoResults?.timeframe || 36,
        confidenceLevel: analytics?.summary?.confidenceLevel || 'Medium',
        keyRecommendations: analytics?.summary?.recommendations?.slice(0, 3) || []
      },
      costAnalysis: {
        onPremiseTCO: tcoResults?.onPremiseTCO || 0,
        cloudMonthly: tcoResults?.cloudMonthly || 0,
        cloudTCO: tcoResults?.cloudTCO || 0,
        migrationCost: tcoResults?.migrationCost || 0,
        totalCloudTCO: tcoResults?.totalCloudTCO || 0,
        savings: tcoResults?.savings || 0,
        costBreakdown: tcoResults?.cloudCostBreakdown || {}
      },
      riskAnalysis: {
        riskAdjustedTCO: analytics?.riskAdjusted?.riskAdjustedTCO || 0,
        riskFactors: analytics?.riskAdjusted?.riskFactors || {},
        riskMultiplier: analytics?.riskAdjusted?.riskMultiplier || 1.0
      },
      sensitivityAnalysis: {
        onPremise: analytics?.sensitivity?.onPremise || null,
        cloud: analytics?.sensitivity?.cloud || null,
        migration: analytics?.sensitivity?.migration || null
      },
      forecasting: {
        forecastData: analytics?.forecast || [],
        breakEvenPoint: analytics?.summary?.breakEvenPoint || null
      },
      environmentalImpact: {
        footprint: analytics?.footprint || {},
        reductionPercent: analytics?.footprint?.percentReduction || 0
      }
    };
  };

  // Generate PDF report
  const generatePDFReport = async () => {
    setIsGenerating(true);
    
    try {
      const reportData = generateReportData();
      if (!reportData) {
        throw new Error('No analysis data available for report');
      }

      const doc = new jsPDF('p', 'mm', 'a4');
      let yPosition = 20;

      // Header
      doc.setFontSize(22);
      doc.setTextColor(40, 40, 40);
      doc.text('Cloud Migration TCO Analysis Report', 105, yPosition, null, null, 'center');
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated by: ${companyName}`, 20, yPosition + 10);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 190, yPosition + 10, null, null, 'right');
      
      yPosition += 25;

      // Executive Summary
      doc.setFontSize(16);
      doc.setTextColor(0, 102, 204);
      doc.text('Executive Summary', 20, yPosition);
      
      yPosition += 10;
      doc.setFontSize(12);
      doc.setTextColor(40, 40, 40);
      
      doc.text(`Total Cloud Investment: $${reportData.executiveSummary.totalInvestment.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 20, yPosition);
      yPosition += 8;
      doc.text(`Projected Savings: $${reportData.executiveSummary.totalSavings.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 20, yPosition);
      yPosition += 8;
      doc.text(`Return on Investment: ${reportData.executiveSummary.roi.toFixed(2)}%`, 20, yPosition);
      yPosition += 8;
      doc.text(`Analysis Period: ${reportData.executiveSummary.timeframe} months`, 20, yPosition);
      yPosition += 8;
      doc.text(`Confidence Level: ${reportData.executiveSummary.confidenceLevel}`, 20, yPosition);
      yPosition += 15;

      // Cost Analysis Table
      doc.setFontSize(16);
      doc.setTextColor(0, 102, 204);
      doc.text('Cost Analysis', 20, yPosition);
      yPosition += 10;

      doc.autoTable({
        head: [['Cost Component', 'Amount']],
        body: [
          ['On-Premise TCO', `$${reportData.costAnalysis.onPremiseTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Cloud Recurring Costs', `$${reportData.costAnalysis.cloudTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Migration Costs', `$${reportData.costAnalysis.migrationCost.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Total Cloud TCO', `$${reportData.costAnalysis.totalCloudTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Net Savings', `$${reportData.costAnalysis.savings.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]
        ],
        startY: yPosition,
        margin: { left: 20 },
        styles: { fontSize: 10 }
      });
      
      yPosition = doc.lastAutoTable.finalY + 15;

      // Risk Analysis
      doc.setFontSize(16);
      doc.setTextColor(0, 102, 204);
      doc.text('Risk Analysis', 20, yPosition);
      yPosition += 10;
      
      doc.text(`Risk-Adjusted TCO: $${reportData.riskAnalysis.riskAdjustedTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 20, yPosition);
      yPosition += 8;
      doc.text(`Risk Multiplier: ${reportData.riskAnalysis.riskMultiplier.toFixed(2)}x`, 20, yPosition);
      yPosition += 15;

      // Recommendations
      if (reportData.executiveSummary.keyRecommendations.length > 0) {
        doc.setFontSize(16);
        doc.setTextColor(0, 102, 204);
        doc.text('Key Recommendations', 20, yPosition);
        yPosition += 10;

        reportData.executiveSummary.keyRecommendations.forEach((rec, index) => {
          doc.text(`${index + 1}. ${rec.recommendation}`, 20, yPosition);
          yPosition += 8;
        });
      }

      // Environmental Impact
      if (reportData.environmentalImpact.footprint.totalReduction) {
        yPosition += 15;
        doc.setFontSize(16);
        doc.setTextColor(0, 102, 204);
        doc.text('Environmental Impact', 20, yPosition);
        yPosition += 10;
        
        doc.text(`Carbon Footprint Reduction: ${reportData.environmentalImpact.reductionPercent.toFixed(1)}%`, 20, yPosition);
        yPosition += 8;
        doc.text(`Equivalent to removing ${(reportData.environmentalImpact.reductionPercent * 0.5).toFixed(0)} cars from the road annually`, 20, yPosition);
      }

      // Footer
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('This report contains confidential information and should be shared appropriately.', 105, 280, null, null, 'center');

      // Save the PDF
      doc.save(`Cloud-Migration-TCO-Report-${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF report: ' + error.message);
    } finally {
      setIsGenerating(false);
    }
  };

  // Generate Excel report (as JSON for now, could be extended to actual Excel)
  const generateExcelReport = () => {
    setIsGenerating(true);
    
    try {
      const reportData = generateReportData();
      if (!reportData) {
        throw new Error('No analysis data available for report');
      }

      const excelData = {
        metadata: {
          companyName: companyName,
          generatedDate: new Date().toISOString(),
          reportType: 'TCO Analysis',
          format: 'Excel/CSV'
        },
        executiveSummary: reportData.executiveSummary,
        costAnalysis: reportData.costAnalysis,
        riskAnalysis: reportData.riskAnalysis,
        sensitivityAnalysis: reportData.sensitivityAnalysis,
        forecasting: reportData.forecasting,
        environmentalImpact: reportData.environmentalImpact
      };

      const dataStr = JSON.stringify(excelData, null, 2);
      const blob = new Blob([dataStr], { type: 'application/json' });
      saveAs(blob, `Cloud-Migration-TCO-Data-${new Date().toISOString().split('T')[0]}.json`);
    } catch (error) {
      console.error('Error generating Excel report:', error);
      alert('Error generating Excel report: ' + error.message);
    } finally {
      setIsGenerating(false);
    }
  };

  // Generate PowerPoint report (as PDF for now)
  const generatePowerPointReport = () => {
    setIsGenerating(true);
    
    try {
      const reportData = generateReportData();
      if (!reportData) {
        throw new Error('No analysis data available for report');
      }

      const doc = new jsPDF('l', 'mm', 'a4'); // Landscape A4 for presentation format
      
      // Slide 1: Title Slide
      doc.setFontSize(28);
      doc.setTextColor(0, 102, 204);
      doc.text('Cloud Migration TCO Analysis', 148, 100, null, null, 'center');
      
      doc.setFontSize(16);
      doc.setTextColor(40, 40, 40);
      doc.text(`${companyName} - Cloud Strategy`, 148, 120, null, null, 'center');
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(`Analysis Period: ${reportData.executiveSummary.timeframe} months`, 148, 135, null, null, 'center');
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 148, 145, null, null, 'center');

      doc.addPage();

      // Slide 2: Executive Summary
      doc.setFontSize(20);
      doc.setTextColor(0, 102, 204);
      doc.text('Executive Summary', 148, 20, null, null, 'center');
      
      doc.setFontSize(14);
      doc.setTextColor(40, 40, 40);
      
      doc.text(`Total Investment: $${reportData.executiveSummary.totalInvestment.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 20, 50);
      doc.text(`Total Savings: $${reportData.executiveSummary.totalSavings.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 20, 70);
      doc.text(`ROI: ${reportData.executiveSummary.roi.toFixed(2)}%`, 20, 90);
      doc.text(`Confidence Level: ${reportData.executiveSummary.confidenceLevel}`, 20, 110);

      doc.addPage();

      // Slide 3: Cost Comparison
      doc.setFontSize(20);
      doc.setTextColor(0, 102, 204);
      doc.text('Cost Comparison', 148, 20, null, null, 'center');

      doc.autoTable({
        head: [['Cost Component', 'Amount']],
        body: [
          ['On-Premise TCO', `$${reportData.costAnalysis.onPremiseTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Cloud Recurring', `$${reportData.costAnalysis.cloudTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Migration Costs', `$${reportData.costAnalysis.migrationCost.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Total Cloud TCO', `$${reportData.costAnalysis.totalCloudTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`],
          ['Net Savings', `$${reportData.costAnalysis.savings.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]
        ],
        startY: 40,
        margin: { left: 20, right: 20 },
        styles: { fontSize: 12 }
      });

      doc.addPage();

      // Slide 4: Key Recommendations
      doc.setFontSize(20);
      doc.setTextColor(0, 102, 204);
      doc.text('Key Recommendations', 148, 20, null, null, 'center');

      if (reportData.executiveSummary.keyRecommendations.length > 0) {
        let yPos = 50;
        reportData.executiveSummary.keyRecommendations.forEach((rec, index) => {
          doc.setFontSize(14);
          doc.text(`${index + 1}. ${rec.recommendation}`, 20, yPos);
          yPos += 15;
          
          doc.setFontSize(10);
          doc.setTextColor(100, 100, 100);
          doc.text(rec.potentialSavings, 20, yPos - 3);
          doc.setTextColor(40, 40, 40);
          yPos += 10;
        });
      }

      doc.save(`Cloud-Migration-Presentation-${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('Error generating PowerPoint report:', error);
      alert('Error generating PowerPoint report: ' + error.message);
    } finally {
      setIsGenerating(false);
    }
  };

  // Generate Word report
  const generateWordReport = () => {
    setIsGenerating(true);
    
    try {
      const reportData = generateReportData();
      if (!reportData) {
        throw new Error('No analysis data available for report');
      }

      // Create a detailed Word document as a text file (in a real app, we'd use a proper Word library)
      let wordContent = `
CLOUD MIGRATION TCO ANALYSIS REPORT
====================================

Prepared for: ${companyName}
Analysis Period: ${reportData.executiveSummary.timeframe} months
Generated on: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
-----------------
Total Cloud Investment: $${reportData.executiveSummary.totalInvestment.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
Projected Savings: $${reportData.executiveSummary.totalSavings.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
Return on Investment: ${reportData.executiveSummary.roi.toFixed(2)}%
Confidence Level: ${reportData.executiveSummary.confidenceLevel}

COST ANALYSIS
-------------
On-Premise TCO: $${reportData.costAnalysis.onPremiseTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
Cloud Recurring Costs: $${reportData.costAnalysis.cloudTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
Migration Costs: $${reportData.costAnalysis.migrationCost.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
Total Cloud TCO: $${reportData.costAnalysis.totalCloudTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
Net Savings: $${reportData.costAnalysis.savings.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}

RISK ANALYSIS
-------------
Risk-Adjusted TCO: $${reportData.riskAnalysis.riskAdjustedTCO.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
Risk Multiplier: ${reportData.riskAnalysis.riskMultiplier.toFixed(2)}x

KEY RECOMMENDATIONS
-------------------
`;

      if (reportData.executiveSummary.keyRecommendations.length > 0) {
        reportData.executiveSummary.keyRecommendations.forEach((rec, index) => {
          wordContent += `${index + 1}. ${rec.recommendation}\n   - Potential Savings: ${rec.potentialSavings}\n\n`;
        });
      }

      wordContent += `
ENVIRONMENTAL IMPACT
-------------------
Carbon Footprint Reduction: ${reportData.environmentalImpact.reductionPercent.toFixed(1)}%
Equivalent to removing ${(reportData.environmentalImpact.reductionPercent * 0.5).toFixed(0)} cars from the road annually

`;

      const blob = new Blob([wordContent], { type: 'application/msword' });
      saveAs(blob, `Cloud-Migration-TCO-Report-${new Date().toISOString().split('T')[0]}.doc`);
    } catch (error) {
      console.error('Error generating Word report:', error);
      alert('Error generating Word report: ' + error.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGenerateReport = () => {
    switch (reportFormat) {
      case 'pdf':
        generatePDFReport();
        break;
      case 'excel':
        generateExcelReport();
        break;
      case 'powerpoint':
        generatePowerPointReport();
        break;
      case 'word':
        generateWordReport();
        break;
      default:
        generatePDFReport();
    }
  };

  return (
    <div className="advanced-report-generator">
      <div className="report-header">
        <h3>📊 Advanced Reporting & Export</h3>
      </div>

      <div className="report-controls">
        <div className="row">
          <div className="col-md-6">
            <div className="mb-3">
              <label className="form-label">Report Format</label>
              <select
                className="form-control"
                value={reportFormat}
                onChange={(e) => setReportFormat(e.target.value)}
              >
                <option value="pdf">PDF (Portable Document)</option>
                <option value="excel">Excel (Data)</option>
                <option value="powerpoint">PowerPoint (Presentation)</option>
                <option value="word">Word (Document)</option>
              </select>
            </div>
          </div>
          <div className="col-md-6">
            <div className="mb-3">
              <label className="form-label">Report Type</label>
              <select
                className="form-control"
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
              >
                <option value="executive">Executive Summary</option>
                <option value="detailed">Detailed Analysis</option>
                <option value="technical">Technical Specifications</option>
                <option value="financial">Financial Deep Dive</option>
              </select>
            </div>
          </div>
        </div>

        <button 
          className="btn btn-primary btn-lg w-100"
          onClick={handleGenerateReport}
          disabled={isGenerating}
        >
          {isGenerating ? (
            <>
              <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
              Generating Report...
            </>
          ) : (
            <>
              📤 Generate {reportFormat.toUpperCase()} Report
            </>
          )}
        </button>
      </div>

      <div className="report-preview">
        <h4>📊 Report Preview</h4>
        {analysisData ? (
          <div className="preview-content">
            <div className="preview-metrics">
              <div className="metric-card">
                <div className="metric-value">${(analysisData.tcoResults?.totalCloudTCO || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                <div className="metric-label">Total Cloud Investment</div>
              </div>
              <div className="metric-card">
                <div className="metric-value">${(analysisData.tcoResults?.savings || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
                <div className="metric-label">Projected Savings</div>
              </div>
              <div className="metric-card">
                <div className="metric-value">{(analysisData.tcoResults?.roi || 0).toFixed(2)}%</div>
                <div className="metric-label">ROI</div>
              </div>
            </div>
            
            {analysisData.analytics?.summary?.recommendations?.length > 0 && (
              <div className="key-recommendations">
                <h5>Key Recommendations:</h5>
                <ul>
                  {analysisData.analytics.summary.recommendations.slice(0, 3).map((rec, idx) => (
                    <li key={idx}>{rec.recommendation} ({rec.potentialSavings})</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        ) : (
          <div className="no-data">
            <p>No analysis data available for report generation. Please complete a TCO calculation first.</p>
          </div>
        )}
      </div>

      <div className="report-features">
        <h4>📋 Report Features</h4>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">📈</div>
            <h5>Executive Summary</h5>
            <p>High-level overview with key metrics and recommendations</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">💰</div>
            <h5>Financial Analysis</h5>
            <p>Detailed cost breakdown and ROI calculations</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">📊</div>
            <h5>Data Visualization</h5>
            <p>Interactive charts and graphs</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🛡️</div>
            <h5>Risk Assessment</h5>
            <p>Comprehensive risk analysis and mitigation strategies</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🌍</div>
            <h5>Environmental Impact</h5>
            <p>Carbon footprint analysis</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🎯</div>
            <h5>Optimization Recommendations</h5>
            <p>AI-powered suggestions for cost optimization</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdvancedReportGenerator;