// Demo Data for showcasing the application

export const demoWorkloads = [
  {
    id: 1,
    name: 'web-frontend-prod',
    type: 'application',
    os: 'linux',
    cpu: 4,
    memory: 16,
    storage: 100,
    monthlyTraffic: 500,
    dependencies: 'api-gateway, auth-service',
  },
  {
    id: 2,
    name: 'api-gateway',
    type: 'application',
    os: 'linux',
    cpu: 8,
    memory: 32,
    storage: 50,
    monthlyTraffic: 1200,
    dependencies: 'user-service, order-service, product-service',
  },
  {
    id: 3,
    name: 'user-service',
    type: 'container',
    os: 'linux',
    cpu: 4,
    memory: 8,
    storage: 20,
    monthlyTraffic: 300,
    dependencies: 'postgres-users',
  },
  {
    id: 4,
    name: 'order-service',
    type: 'container',
    os: 'linux',
    cpu: 6,
    memory: 16,
    storage: 30,
    monthlyTraffic: 450,
    dependencies: 'postgres-orders, redis-cache',
  },
  {
    id: 5,
    name: 'product-service',
    type: 'container',
    os: 'linux',
    cpu: 4,
    memory: 12,
    storage: 40,
    monthlyTraffic: 600,
    dependencies: 'postgres-products',
  },
  {
    id: 6,
    name: 'auth-service',
    type: 'application',
    os: 'linux',
    cpu: 2,
    memory: 8,
    storage: 20,
    monthlyTraffic: 200,
    dependencies: 'postgres-users',
  },
  {
    id: 7,
    name: 'postgres-users',
    type: 'database',
    os: 'linux',
    cpu: 8,
    memory: 64,
    storage: 500,
    monthlyTraffic: 100,
    dependencies: '',
  },
  {
    id: 8,
    name: 'postgres-orders',
    type: 'database',
    os: 'linux',
    cpu: 16,
    memory: 128,
    storage: 2000,
    monthlyTraffic: 150,
    dependencies: '',
  },
  {
    id: 9,
    name: 'postgres-products',
    type: 'database',
    os: 'linux',
    cpu: 8,
    memory: 64,
    storage: 800,
    monthlyTraffic: 80,
    dependencies: '',
  },
  {
    id: 10,
    name: 'redis-cache',
    type: 'database',
    os: 'linux',
    cpu: 4,
    memory: 32,
    storage: 100,
    monthlyTraffic: 500,
    dependencies: '',
  },
  {
    id: 11,
    name: 'file-storage',
    type: 'storage',
    os: 'linux',
    cpu: 2,
    memory: 8,
    storage: 5000,
    monthlyTraffic: 2000,
    dependencies: '',
  },
  {
    id: 12,
    name: 'backup-storage',
    type: 'storage',
    os: 'linux',
    cpu: 1,
    memory: 4,
    storage: 10000,
    monthlyTraffic: 500,
    dependencies: '',
  },
  {
    id: 13,
    name: 'analytics-vm',
    type: 'vm',
    os: 'linux',
    cpu: 16,
    memory: 64,
    storage: 1000,
    monthlyTraffic: 300,
    dependencies: 'postgres-orders, postgres-products',
  },
  {
    id: 14,
    name: 'reporting-service',
    type: 'application',
    os: 'linux',
    cpu: 4,
    memory: 16,
    storage: 200,
    monthlyTraffic: 150,
    dependencies: 'analytics-vm',
  },
  {
    id: 15,
    name: 'legacy-windows-app',
    type: 'vm',
    os: 'windows',
    cpu: 8,
    memory: 32,
    storage: 500,
    monthlyTraffic: 100,
    dependencies: 'legacy-db',
  },
  {
    id: 16,
    name: 'legacy-db',
    type: 'database',
    os: 'windows',
    cpu: 12,
    memory: 96,
    storage: 1500,
    monthlyTraffic: 80,
    dependencies: '',
  },
];

export const demoLandingZoneConfig = {
  organizationId: '123456789012',
  billingAccountId: 'ABCDEF-123456-ABCDEF',
  projects: [
    { name: 'prod', displayName: 'Production', environment: 'production' },
    { name: 'staging', displayName: 'Staging', environment: 'staging' },
    { name: 'dev', displayName: 'Development', environment: 'development' },
  ],
  folders: ['infrastructure', 'applications', 'data', 'security'],
  networkConfig: {
    vpcName: 'main-vpc',
    region: 'us-central1',
    subnets: [
      { name: 'web-subnet', cidr: '10.0.1.0/24', region: 'us-central1' },
      { name: 'app-subnet', cidr: '10.0.2.0/24', region: 'us-central1' },
      { name: 'db-subnet', cidr: '10.0.3.0/24', region: 'us-central1' },
      { name: 'mgmt-subnet', cidr: '10.0.4.0/24', region: 'us-central1' },
    ],
    enableCloudNAT: true,
    enableCloudRouter: true,
    enablePrivateGoogleAccess: true,
  },
  securityConfig: {
    enableOrgPolicies: true,
    enableVPCServiceControls: true,
    enableCloudArmor: true,
    requireSSL: true,
    enableDLP: true,
  },
  computeConfig: {
    enableGKE: true,
    gkeVersion: 'latest',
    gkeNodePools: 2,
    gkeNodesPerPool: 5,
    enableComputeEngine: true,
    defaultMachineType: 'n2-standard-4',
  },
  storageConfig: {
    enableCloudStorage: true,
    storageBuckets: ['artifacts', 'data', 'backups', 'logs', 'media'],
    enableCloudSQL: true,
    sqlVersion: 'POSTGRES_14',
    enableFirestore: true,
  },
  observabilityConfig: {
    enableCloudMonitoring: true,
    enableCloudLogging: true,
    logRetentionDays: 90,
    enableCloudTrace: true,
    enableCloudProfiler: true,
  },
};

export const demoOnPremiseCosts = {
  hardware: 5000,
  software: 2000,
  maintenance: 1500,
  labor: 8000,
  power: 1200,
  cooling: 800,
  datacenter: 2500,
};

export const demoCloudCosts = {
  aws: {
    ec2: 3500,
    s3: 800,
    rds: 2200,
    vpc: 400,
    cloudwatch: 300,
  },
  azure: {
    virtualMachines: 3200,
    blobStorage: 700,
    sqlDatabase: 2000,
    networking: 450,
    monitoring: 250,
  },
  gcp: {
    compute: 2800,
    storage: 600,
    networking: 350,
    database: 1800,
    monitoring: 200,
  },
};

export const demoMigrationCosts = {
  assessment: 15000,
  tools: 8000,
  training: 12000,
  consulting: 25000,
};

export const loadDemoData = () => ({
  workloads: demoWorkloads,
  landingZoneConfig: demoLandingZoneConfig,
  onPremise: demoOnPremiseCosts,
  aws: demoCloudCosts.aws,
  azure: demoCloudCosts.azure,
  gcp: demoCloudCosts.gcp,
  migration: demoMigrationCosts,
  timeframe: 36,
});
